name: Maven Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GITHUB_ACTOR }}</username>
                <password>${{ secrets.MAVEN_DEPLOY_PASSWORD }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: List files
        run: ls -R

      - name: Build and Test with Maven
        run: mvn clean install -B -DskipTests

      - name: Deploy to GitHub Packages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: mvn deploy -DskipTests
