name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.USERNAME_MVN }}</username>
                <password>${{ secrets.TOKEN_MVN }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.USERNAME_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.USERNAME_DOCKER_HUB }}/ezcommerce-backend:${{github.ref_name}}"